if(EXISTS "/home/alejandro/Escritorio/Mnemis/build-baseline/tests/mnemis_tests[1]_tests.cmake")
  include("/home/alejandro/Escritorio/Mnemis/build-baseline/tests/mnemis_tests[1]_tests.cmake")
else()
  add_test(mnemis_tests_NOT_BUILT mnemis_tests_NOT_BUILT)
endif()
